config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: "tasks#index"
  get '/tasks/new', to: "tasks#new"
  get '/tasks/:id', to: "tasks#show", as: "task"
  post '/tasks', to: "tasks#create"
  get 'task/:id/edit', to: "tasks#edit"
  patch 'tasks/:id', to: "tasks#update"
  delete 'tasks/:id', to: "tasks#destroy", as: "delete_task"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task_path(task)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<!-- <form action="/tasks" method="post">
  <label for="title">Task title</label>
  <input type="text" name="title" id="title">
  <label for="description">Task description</label>
  <input type="text" name="description" id="description">
  <label for="completed">is Completed ?</label>
  <input type="checkbox" name="completed" id="completed">
  <input type="submit">
</form> -->

<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.label :completed %>
<%= f.check_box :completed %>
<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <% if task.completed %>
    <input type="checkbox" checked>
  <% else %>
    <input type="checkbox">
  <% end %>
  <%= link_to task.title, task_path(task) %>
  <br>
<% end %>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<h1> <%=  @task.title%></h1>

<%= link_to "Delete", delete_task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>